### ISSUE TITLE
Live TV Playback Fails 

### ISSUE THREAD

**Issue by theguymadmax** [jellyfin/Swiftfin#1183]
### Describe the bug

As detailed in this [forum post](https://forum.jellyfin.org/t-swiftfin-on-ios-won-t-play-live-tv?pid=32750#pid32750), attempting to load Live TV in Swiftfin on iOS results in a playback failure. However, Live TV functions correctly on all other Jellyfin clients, including the iOS mobile app, Android TV, JMP, and WebUI (Firefox and Chrome).

Full logs: [here](https://pastebin.com/raw/8izg7XJJ)
Relevant server logs:
```[19:48:31] [ERR] [6] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request. URL POST /Items/bdf1a9953d0110ed61f7bf1f43286cd0/PlaybackInfo.
System.InvalidCastException: Unable to cast object of type 'MediaBrowser.Controller.LiveTv.LiveTvProgram' to type 'MediaBrowser.Controller.Entities.IHasMediaSources'.
   at Emby.Server.Implementations.Library.MediaSourceManager.GetStaticMediaSources(BaseItem item, Boolean enablePathSubstitution, User user)
   at Emby.Server.Implementations.Library.MediaSourceManager.GetPlaybackMediaSources(BaseItem item, User user, Boolean allowMediaProbe, Boolean enablePathSubstitution, CancellationToken cancellationToken)
   at Jellyfin.Api.Helpers.MediaInfoHelper.GetPlaybackInfo(BaseItem item, User user, String mediaSourceId, String liveStreamId)
   at Jellyfin.Api.Controllers.MediaInfoController.GetPostedPlaybackInfo(Guid itemId, Nullable`1 userId, Nullable`1 maxStreamingBitrate, Nullable`1 startTimeTicks, Nullable`1 audioStreamIndex, Nullable`1 subtitleStreamIndex, Nullable`1 maxAudioChannels, String mediaSourceId, String liveStreamId, Nullable`1 autoOpenLiveStream, Nullable`1 enableDirectPlay, Nullable`1 enableDirectStream, Nullable`1 enableTranscoding, Nullable`1 allowVideoStreamCopy, Nullable`1 allowAudioStreamCopy, PlaybackInfoDto playbackInfoDto)
   at lambda_method1104(Closure, Object)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Jellyfin.Api.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Api.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Api.Middleware.IPBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Api.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Api.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Api.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Api.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Jellyfin.Api.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
   at Jellyfin.Api.Middleware.ExceptionMiddleware.Invoke(HttpContext context)'''

Additional Hardware info: HDHR4-2US 


### Application version

1.1 (78)

### Where did you install the app from?

App Store

### Device information

IPhone 13 Pro

### OS version

iOS 17.6.1

### Jellyfin server version

10.9.9

**Comment by chemicalsam** [comment]
I am also having this issue. I cannot play any live tv in Swiftfin. It also doesn’t play reliably in the standard Jellyfin app either on iOS. Not sure what’s going on.

**Comment by NetworkGuy44** [comment]
First, appreciate all the work that has been done. I notice the same issue as stated. Jellyfin iOS client works well from what I can tell and the look is just like the web client which looks great. Anyway to make a port of the jellyfin iOS client available for tvOS while Swiftfin development continues?

**Comment by thornbill** [comment]
> First, appreciate all the work that has been done. I notice the same issue as stated. Jellyfin iOS client works well from what I can tell and the look is just like the web client which looks great. Anyway to make a port of the jellyfin iOS client available for tvOS while Swiftfin development continues?

No. Apple does not allow webviews in tvOS apps.

**Comment by nds2204** [comment]
I'm interested solving this issue, can someone indicates me where must I look ? Thanks !

**Comment by JPKribs** [comment]
> I'm interested solving this issue, can someone indicates me where must I look ? Thanks !

Thank you for reaching out! For now, I would hold off on any issue with the green `Playback` until after https://github.com/jellyfin/Swiftfin/pull/1581. 

This PR _should_ resolve a lot of these issues but primarily it will change how the playback APIs work. So, anything playback related would need to be redone post-1581 regardless.

**Comment by nds2204** [comment]
> > I'm interested solving this issue, can someone indicates me where must I look ? Thanks !
> 
> Thank you for reaching out! For now, I would hold off on any issue with the green `Playback` until after https://github.com/jellyfin/Swiftfin/pull/1581. 
> 
> This PR _should_ resolve a lot of these issues but primarily it will change how the playback APIs work. So, anything playback related would need to be redone post-1581 regardless.

Alright, Thanks for your feedback ! Then I guess I should wait and see ! Do not hesitate if I can help elsewhere for now !

**Comment by JPKribs** [comment]
> Do not hesitate if I can help elsewhere for now

If you're interested, I try to keep this up to date:

https://github.com/jellyfin/Swiftfin/discussions/1503

That being said, I need to do a bit of cleanup and add some new items. I'll try to get that cleaned up today/tomorrow. But that should be a good source for items!

---

The list isn't comprehensive (see all issues) but it should be up to date for good items to familiarize yourself with the codebase! If you have any questions feel free to ping me in that thread and I can help answer anything there.

**Comment by travisghansen** [comment]
I also experience this with `10.10.7`. Works in Jellyfin but fails with the error mentioned in the report for Swiftfin iOS.

**Comment by coder747-8i** [comment]
I am having these exact symptoms… While live TV works everywhere else, including Swiftfin Apple TV version, it refuses to work on iOS, even after much tinkering. I'm anxious to see when this will be resolved and also when the new TV update will come out.
(also I am aware that the Apple TV version is several versions behind the iOS version specifically 1.0.1 while the iPhone version is 1.4)

Although I definitely can live without it!🤗 

Thanks for all the work everybody puts into this project!

**Comment by theguymadmax** [comment]
Retested this issue on Jellyfin 10.11.4, Swiftfin 1.4, Live TV  source: hdhomerun

Steps:

1. Select the Media icon, then choose Live TV
2. Presented with the Live TV homepage: Channels link on top, then On Now, Series, Movies (all with guide data and thumbnails).
3. None of the On Now, Series, or Movies media thumbnails are clickable. - No Errors in the log.
4. Clicking on the channels link at the top, you are presented with a detailed list view of live TV media. These items are clickable and play without error. 


Note: the channel doesn't get released after closing it.  It keeps transcoding on the server. So after opening 2 channels (2-channel tuner), on the third channel, you'll get an error (see below).  Seems to be this [issue](https://github.com/jellyfin/jellyfin/issues/15769#issuecomment-3647126459).




<details>
  <summary>Log Error</summary>

```
jellyfintest1  | [14:00:26] [ERR] [116] Jellyfin.LiveTv.TunerHosts.HdHomerun.HdHomerunHost: Error opening tuner
jellyfintest1  | MediaBrowser.Controller.LiveTv.LiveTvConflictException: HDHomeRun simultaneous stream limit has been reached.
jellyfintest1  |    at Jellyfin.LiveTv.TunerHosts.HdHomerun.HdHomerunHost.GetChannelStream(TunerHostInfo tunerHost, ChannelInfo channel, String streamId, IList`1 currentLiveStreams, CancellationToken cancellationToken)
jellyfintest1  |    at Jellyfin.LiveTv.TunerHosts.BaseTunerHost.GetChannelStream(String channelId, String streamId, IList`1 currentLiveStreams, CancellationToken cancellationToken)
jellyfintest1  | [14:00:26] [ERR] [116] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request. URL POST /Items/170cfde27a1f6857f6a50b50e07751b7/PlaybackInfo.
jellyfintest1  | MediaBrowser.Controller.LiveTv.LiveTvConflictException: Unable to find host to play channel
jellyfintest1  |    at Jellyfin.LiveTv.TunerHosts.BaseTunerHost.GetChannelStream(String channelId, String streamId, IList`1 currentLiveStreams, CancellationToken cancellationToken)
jellyfintest1  |    at Jellyfin.LiveTv.DefaultLiveTvService.GetChannelStreamWithDirectStreamProvider(String channelId, String streamId, List`1 currentLiveStreams, CancellationToken cancellationToken)
jellyfintest1  |    at Jellyfin.LiveTv.LiveTvMediaSourceProvider.GetChannelStream(String id, String mediaSourceId, List`1 currentLiveStreams, CancellationToken cancellationToken)
jellyfintest1  |    at Jellyfin.LiveTv.LiveTvMediaSourceProvider.OpenMediaSource(String openToken, List`1 currentLiveStreams, CancellationToken cancellationToken)
jellyfintest1  |    at Emby.Server.Implementations.Library.MediaSourceManager.OpenLiveStreamInternal(LiveStreamRequest request, CancellationToken cancellationToken)
jellyfintest1  |    at Emby.Server.Implementations.Library.MediaSourceManager.OpenLiveStream(LiveStreamRequest request, CancellationToken cancellationToken)
jellyfintest1  |    at Jellyfin.Api.Helpers.MediaInfoHelper.OpenMediaSource(HttpContext httpContext, LiveStreamRequest request)
jellyfintest1  |    at Jellyfin.Api.Controllers.MediaInfoController.GetPostedPlaybackInfo(Guid itemId, Nullable`1 userId, Nullable`1 maxStreamingBitrate, Nullable`1 startTimeTicks, Nullable`1 audioStreamIndex, Nullable`1 subtitleStreamIndex, Nullable`1 maxAudioChannels, String mediaSourceId, String liveStreamId, Nullable`1 autoOpenLiveStream, Nullable`1 enableDirectPlay, Nullable`1 enableDirectStream, Nullable`1 enableTranscoding, Nullable`1 allowVideoStreamCopy, Nullable`1 allowAudioStreamCopy, PlaybackInfoDto playbackInfoDto)
jellyfintest1  |    at lambda_method23497(Closure, Object)
jellyfintest1  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
jellyfintest1  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
jellyfintest1  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
jellyfintest1  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
jellyfintest1  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
jellyfintest1  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
jellyfintest1  | --- End of stack trace from previous location ---
jellyfintest1  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
jellyfintest1  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
jellyfintest1  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
jellyfintest1  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
jellyfintest1  | --- End of stack trace from previous location ---
jellyfintest1  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
jellyfintest1  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
jellyfintest1  |    at Jellyfin.Api.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
jellyfintest1  |    at Jellyfin.Api.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
jellyfintest1  |    at Jellyfin.Api.Middleware.IPBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
jellyfintest1  |    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
jellyfintest1  |    at Jellyfin.Api.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
jellyfintest1  |    at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
jellyfintest1  |    at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
jellyfintest1  |    at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
jellyfintest1  |    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
jellyfintest1  |    at Jellyfin.Api.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
jellyfintest1  |    at Jellyfin.Api.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
jellyfintest1  |    at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
jellyfintest1  |    at Jellyfin.Api.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
jellyfintest1  |    at Jellyfin.Api.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
jellyfintest1  | [14:00:34] [INF] [12] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: Transcoding kill timer stopped for JobId 74672051d4564f89a33409e240d5ef1c PlaySessionId f86005b69e304b899c00e47d7f5e6038. Killing transcoding
```

</details>

**Comment by theguymadmax** [comment]
In this thread, I reported three issues:
1)  Live TV not working (original issue)  - This was fixed
2)  Program view not working in Live TV - Still present
3) Live TV tuner not being released - Fixed with https://github.com/jellyfin/Swiftfin/pull/2062 and  will also be handled for any other clients that had this issue with a server-side fix https://github.com/jellyfin/jellyfin/pull/17178

I will close this ticket and open a new one specific to issue `#2`

Note: #1355 can also be closed, as it was the same issue as `#3`
