### ISSUE TITLE
Error in pod install

### ISSUE THREAD

**Issue by BraveCaptain** [jellyfin/Swiftfin#388]
### Podfile

```ruby
use_frameworks!
inhibit_all_warnings!
def shared_pods
  pod 'SwiftGen'
end

target 'Swiftfin iOS' do
  platform :ios, '15.0'
  shared_pods
  pod 'google-cast-sdk'
  pod 'MobileVLCKit'
  pod 'SwizzleSwift'
end
target 'Swiftfin tvOS' do
  platform :tvos, '15.0'
  shared_pods
  pod 'TVVLCKit'
end
target 'Swiftfin Widget' do
  platform :ios, '15.0'
  shared_pods
end
```

### Error

```
JSON::ParserError - 809: unexpected token at '{
  "name": "MobileVLCKit",
  "version": "3.3.18b9",
  "summary": "MobileVLCKit is an Objective-C wrapper for libvlc's external interface on iOS.",
  "homepage": "https://code.videolan.org/videolan/VLCKit",
  "license": {
    "type": "LGPL v2.1",
    "file": "COPYING.txt"
  },
  "documentation_url": "https://wiki.videolan.org/VLCKit/",
  "social_media_url": "https://twitter.com/videolan",
  "platforms": {
    "ios": "8.4"
  },
  "authors": {
    "Pierre d'Herbemont": "pdherbemont@videolan.org",
    "Felix Paul Kühne": "fkuehne@videolan.org",
    "Carola Nitz": "nitz.carola@googlemail.com",
    "Jean-Baptiste Kempf": "jb@videolan.org",
    "Rafaël Carré": "funman@videolan.org",
    "Faustino E. Osuna": "riquedafreak@videolan.org",
    "Rémi Denis-Courmont": "remi@remlab.net",
    "Faustino Osuna": "riquedafreak@videolan.org",
    "Tanguy Krotoff": "tkrotoff@gmail.com",
    "VideoLAN": "videolan@videolan.org",
    "Derk-Jan Hartman": "hartman@videolan.org",
    "Jean-Paul Saman": "jpsaman@videolan.org",
    "Malte Tancred": "malte@frontbase.com",
    "Mike Schrag": "mschrag@pobox.com",
    "Sebastien Zwickert": "dilaroga@free.fr",
    "Toralf Niebuhr": "gmthor85@aim.com",
    "Emmanuel de Roux": "lostbread@free.fr",
    "Daniel Mierswa": "impulze@impulze.org",
    "Rune Botten": "rbotten@gmail.com",
    "Konstantin Pavlov": "thresh@videolan.org",
    "Pere Orga": "gotrunks@gmail.com",
    "Philippe Coent": "philippe.coent@gmail.com",
    "Andrey Utkin": "andrey.krieger.utkin@gmail.com",
    "Brendon Justin": "brendonjustin@gmail.com",
    "Sylver Bruneau": "sylver.bruneau@gmail.com",
    "Gleb Pinigin": "gpinigin@gmail.com",
    "Kuang Rufan": "master@a1983.com.cn",
    "Paul Williamson": "squarefrog@gmail.com",
    "David Fuhrmann": "david.fuhrmann@googlemail.com",
    "Brion Vibber": "brion@pobox.com",
    "Martin Storsjö": "martin@martin.st",
    "Winston Weinert": "winston@ml1.net",
    "Florent Pillet": "fpillet@gmail.com",
    "Paulo Vitor Magacho da Silva": "pvmagacho@gmail.com",
    "James Dumay": "james.w.dumay@gmail.com",
    "Jörg Bleyel": "jbleyel@gmx.net",
    "Aleksandr Matuzok": "sherilynhope@gmail.com",
    "Pierre SAGASPE": "pierre.sagaspe@me.com",
    "Shenggang Hu": "mrhhsg@gmail.com",
    "Filipe Cabecinhas": "vlc@filcab.net",
    "Jeremy Marchand": "kodlian@users'
/Users/tqy/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/json/common.rb:216:in `parse'
/Users/tqy/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/json/common.rb:216:in `parse'
/Users/tqy/.rvm/gems/ruby-3.0.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/specification/json.rb:61:in `from_json'
/Users/tqy/.rvm/gems/ruby-3.0.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/specification.rb:748:in `from_string'
/Users/tqy/.rvm/gems/ruby-3.0.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/specification.rb:722:in `from_file'
/Users/tqy/.rvm/gems/ruby-3.0.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/source.rb:188:in `specification'
/Users/tqy/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.11.2/lib/cocoapods/resolver/lazy_specification.rb:37:in `specification'
/Users/tqy/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/delegate.rb:348:in `block in delegating_block'
/Users/tqy/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/delegate.rb:349:in `block in delegating_block'
/Users/tqy/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.11.2/lib/cocoapods/resolver.rb:178:in `dependencies_for'
/Users/tqy/.rvm/gems/ruby-3.0.0/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:18:in `block in dependencies_for'
/Users/tqy/.rvm/gems/ruby-3.0.0/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:77:in `with_no_such_dependency_error_handling'
/Users/tqy/.rvm/gems/ruby-3.0.0/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:17:in `dependencies_for'
/Users/tqy/.rvm/gems/ruby-3.0.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:809:in `block in group_possibilities'
/Users/tqy/.rvm/gems/ruby-3.0.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:808:in `reverse_each'
/Users/tqy/.rvm/gems/ruby-3.0.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:808:in `group_possibilities'
/Users/tqy/.rvm/gems/ruby-3.0.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:779:in `possibilities_for_requirement'
/Users/tqy/.rvm/gems/ruby-3.0.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:761:in `push_state_for_requirements'
/Users/tqy/.rvm/gems/ruby-3.0.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:744:in `require_nested_dependencies_for'
/Users/tqy/.rvm/gems/ruby-3.0.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:727:in `activate_new_spec'
/Users/tqy/.rvm/gems/ruby-3.0.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:684:in `attempt_to_activate'
/Users/tqy/.rvm/gems/ruby-3.0.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:254:in `process_topmost_state'
/Users/tqy/.rvm/gems/ruby-3.0.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:182:in `resolve'
/Users/tqy/.rvm/gems/ruby-3.0.0/gems/molinillo-0.8.0/lib/molinillo/resolver.rb:43:in `resolve'
/Users/tqy/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.11.2/lib/cocoapods/resolver.rb:94:in `resolve'
/Users/tqy/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:1078:in `block in resolve_dependencies'
/Users/tqy/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.11.2/lib/cocoapods/user_interface.rb:64:in `section'
/Users/tqy/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:1076:in `resolve_dependencies'
/Users/tqy/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
/Users/tqy/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:416:in `analyze'
/Users/tqy/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:241:in `block in resolve_dependencies'
/Users/tqy/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.11.2/lib/cocoapods/user_interface.rb:64:in `section'
/Users/tqy/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:240:in `resolve_dependencies'
/Users/tqy/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:161:in `install!'
/Users/tqy/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.11.2/lib/cocoapods/command/install.rb:52:in `run'
/Users/tqy/.rvm/gems/ruby-3.0.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/Users/tqy/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.11.2/lib/cocoapods/command.rb:52:in `run'
/Users/tqy/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.11.2/bin/pod:55:in `<top (required)>'
/Users/tqy/.rvm/gems/ruby-3.0.0/bin/pod:23:in `load'
/Users/tqy/.rvm/gems/ruby-3.0.0/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Application version

master

### Device information

mac 

### OS version

MacOS 12.0.1

### Jellyfin server version

master

**Comment by BraveCaptain** [comment]
solved this problem by adding a version to MobileVLCKit
